config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#index'
  get '/sessions', to: 'sessions#index'
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new",  as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: 'delete_session'
  delete "/recipes", to: "recipes#destroy", as: 'delete_recipe'
  delete "/userwines", to: "user_wines#destroy", as: 'delete_user_wine'
    delete "/friendships", to: "friendships#destroy", as: 'delete_friendship'

  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :wines
  resources :recipes
  resources :user_wines, only: [:index, :new, :create]
  resources :friendships, only: [:index, :new, :create]


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :wine_recipes
  has_many :wines, through: :wine_recipes
  # validates :name, presence: true, uniqueness: true
  # validates :difficult_level, presence: true
  # validates :cost, presence: true, numericality: {minimum: 0}
  accepts_nested_attributes_for :wines

  def self.difficulty
    [["easy",1],["very easy",2],["very hard",3],["hard",4],["medium",5],["impossible",6]]
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
  #index - all recipes
  #should have a search by feature
    @recipes = Recipe.all
    @user = User.find(session[:user_id])
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = User.find(session[:user_id])
    @difficulty = Recipe.difficulty[@recipe.difficult_level.to_i - 1][0]
  end

  def new
    #users (and admins) can add new wines
    @recipe = Recipe.new
    @difficult = Recipe.difficulty
    @wines = Wine.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = @recipe.errors.full_messages
      redirect_to new_recipe_path
    end

  end

  def edit
    #only admins can edit
    @recipe = Recipe.find(params[:id])
    @difficult = Recipe.difficulty
    @wines = Wine.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      redirect_to edit_recipe_path(@recipe)
    end
  end

  def delete
    #only admins can delete
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :difficult_level, :cost, wine_ids: [], wines_attributes: [:name, :year, :country, :price])
  end

end

app/views/recipes/_form.html.erb
<% if flash[:error] %>
  <ul><% flash[:error].each do |error| %>
    <li><%= error %></li>
  <% end %></ul>
<% end %>


<%= form_for @recipe do |f| %>
  <p><%= f.label :name %><br>
  <%= f.text_field :name %><br></p>
  <p><%= f.label :"Diffculty Level" %><br>
  <%= f.select( :difficult_level, @difficult ) %><br></p>
  <p><%= f.label :"Total Cost"%><br>
  <%= f.number_field :cost %><br></p>
  <p><strong><%= f.label :"Select Vinos To Pair:" %></strong></p>
  <%= f.collection_check_boxes :wine_ids, @wines, :id, :name %><br>
  <p><strong><%= f.label :"Add a new vino:" %></strong></p>
  <%= f.fields_for :wines, @recipe.wines.build do |wines_fields| %>
    <%= wines_fields.text_field :name, placeholder: "Name" %>
    <%= wines_fields.number_field :year, placeholder: "Year"%>
    <%= wines_fields.text_field :country, placeholder: "Country" %>
    <%= wines_fields.number_field :price, placeholder: "Price" %>
  <% end %><br>



  <%= f.submit %><br>
<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe:</h1>
  <h3><%= @recipe.name%> </h3>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1> All Recipes </h1>

<ul><% @recipes.each do |recipe| %>
  <li><%= link_to recipe.name, recipe %> </li>
  <% end %> </ul>

<%= link_to "New Recipe", new_recipe_path %> | <%= link_to "All Wines", wines_path %>  | <%= link_to "My Account", user_path(@user) %>

app/views/recipes/new.html.erb
<h1> Make a New Recipe </h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<p><strong> Difficulty Level: </strong> <%= @difficulty %></p>
<p><strong> Total Cost: </strong> $<%=@recipe.cost%></p>

<p><strong>Vinos To Pair With: </strong></p>
  <ul><% @recipe.wines.each do |wine| %>
    <li><%= link_to wine.name, wine %></li>
  <% end %> </ul>

<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %> | <%= link_to "Delete Recipe", delete_recipe_path%> <br>
<%= link_to "All Recipes", recipes_path %> | <%= link_to "All Wines", wines_path %> | <%= link_to "My Account", user_path(@user) %>