config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#index'
  get '/sessions', to: 'sessions#index'
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new",  as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: 'delete_session'
  delete "/recipes", to: "recipes#destroy", as: 'delete_recipe'
  delete "/userwines", to: "user_wines#destroy", as: 'delete_user_wine'
    delete "/friendships", to: "friendships#destroy", as: 'delete_friendship'

  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :wines
  resources :recipes
  resources :user_wines, only: [:index, :new, :create]
  resources :friendships, only: [:index, :new, :create]


end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_wines
  has_many :wines, through: :user_wines
  has_many :friendships
  has_many :friends, through: :friendships, :foreign_key => 'friend_id'
  accepts_nested_attributes_for :wines
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validate :twenty_one?

  #may need to do some accepts_nested_attributes_for :wine

  def twenty_one?
    oldenough = Date.today - 21.years
    if !(self.birthday < oldenough)
      errors.add(:birthday, "must be older than 21")
    end
  end

  def self.search(search)
    @users= User.where(username: search)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]


  def index
    #index - all users
    #should have a search by feature
    @users = []
    if params[:search]
      @users = User.search(params[:search])
    end
    @user = User.find(session[:user_id])
  end

  def show
    @current_user = User.find(session[:user_id])
    # if logged_in?
    #   flash[:msg] = "Hello #{@current_user.name}!"
    # end
    @user = User.find(params[:id])
  end

  def new
    #users (and admins) can add new wines
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
    flash[:msg] = "Welcome to the BEST VINO APP EVER!"
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    #only admins can edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    byebug
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  def delete
    #only admins can delete
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :birthday)
  end

end

app/views/users/_form.html.erb
<% if flash[:error] %>
  <ul><% flash[:error].each do |error| %>
    <li><%= error %></li>
  <% end %></ul>
<% end %>

<%= form_for @user do |f| %>
  <p><%= f.label :name %><br>
  <%= f.text_field :name %><br></p>
  <p><%= f.label :username %><br>
  <%= f.text_field :username %><br></p>
  <p><%= f.label :password %><br>
  <%= f.password_field :password, placeholder: "Enter Password" %><br>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %><br></p>
  <p><%= f.label :birthday%><br>
  <%= f.date_field :birthday %><br></p>
  <%= f.submit %><br>
<% end %>

app/views/users/edit.html.erb
<h3>Edit Account</h3>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Follow Vino Friends!</h1>


<%= form_tag(users_path, :method => "get", id: "search-form") do %>
    <label> Search by Username</label><br>
    <%= text_field_tag :search, params[:search], placeholder: "Search by Username" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<ul><% @users.each do |user| %>
  <%if user != @user  %>
  <li><%= link_to user.name, user %></li>
  <% end %>
<% end %></ul>

app/views/users/new.html.erb
<h3>Create New Account</h3>
<%= render 'form' %>

app/views/users/show.html.erb
<h3><%= flash[:msg] %></h3>

<h1><%= @user.name %></h1>

<p><strong> Username: </strong> <%=@user.username %></p>
<p><strong> Birthday: </strong><%=@user.birthday.strftime("%B %d, %Y")%></p>

<p><strong>My Saved Vinos: </strong>
  <% if @user.wines == [] %>
    No Saved Wines
  <% else %>
    <ul><% @user.wines.each do |wine| %>
      <li><%= link_to wine.name, wine %> </li>
    <% end %> </ul>
  <% end %></p>

<p><strong>Vino Friends: </strong>
<% if @user.friends == [] %>
  No Friends (womp womp)
<% else %>
  <ul><% @user.friends.each do |friend| %>
    <li><%= link_to friend.name, friend %> </li>
  <% end %> </ul>
<% end %></p>


<% if !@current_user.friendships.find_by(friend: @user) && @user != @current_user %>
  <%= link_to "Add Friend", friendships_path(friend_id: @user.id), method: :post %>
<% elsif @current_user.friendships.find_by(friend: @user) && @user != @current_user %>
  <%=link_to "Delete Friend", delete_friendship_path(@user), method: :delete %>
<% end %>