config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#index'
  get '/sessions', to: 'sessions#index'
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new",  as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: 'delete_session'
  delete "/recipes", to: "recipes#destroy", as: 'delete_recipe'
  delete "/userwines", to: "user_wines#destroy", as: 'delete_user_wine'
    delete "/friendships", to: "friendships#destroy", as: 'delete_friendship'

  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :wines
  resources :recipes
  resources :user_wines, only: [:index, :new, :create]
  resources :friendships, only: [:index, :new, :create]


end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :wine_recipes
  has_many :recipes, through: :wine_recipes
  has_many :user_wines
  has_many :users, through: :user_wines
  accepts_nested_attributes_for :recipes, :reject_if => :all_blank
  accepts_nested_attributes_for :users, :reject_if => :all_blank
  accepts_nested_attributes_for :user_wines, :reject_if => :all_blank

  validates :name, presence: true
  validates :price, presence: true, numericality: {minimum: 0.01}
  validates :country, presence: true

  def user_wines_attributes=(user_wines_attributes)

      user_wine = UserWine.find_or_create_by(user_wines_attributes.values[0]["user_id"])
      user_wine.update(rating: user_wines_attributes.values[0]["rating"])

  end


  def rating
    rating = UserWine.where(wine: self).average("rating").to_f
    if rating == 0.0 || rating == nil
      "This wine has not been rated yet."
    end
    rating
  end







end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  def index
  #index - all wines
  #should have a search by feature
  # byebug
  @wines = Wine.all
  @user = User.find(session[:user_id])
  @top_saved = UserWine.top_saved_wine
  end

  def show
    @wine = Wine.find(params[:id])
    @user = User.find(session[:user_id])

    if UserWine.find_by(wine: @wine, user: @user) && UserWine.find_by(wine: @wine, user: @user).rating != nil
      @user_rating = UserWine.find_by(wine: @wine, user: @user).rating
    else
      @user_rating = "You have not rated this wine."
    end
    @rating = @wine.rating
    @userwine = UserWine.new
  end

  def new
    #users (and admins) can add new wines
    @wine = Wine.new
    @recipes = Recipe.all
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find(session[:user_id])
    @wine = Wine.new(wine_params)
    # @user_wine = UserWine.new(user: @user)

    if @wine.save
      # @wine.user_wines << @user_wine
      redirect_to wine_path(@wine)
    else
      flash[:error] = @wine.errors.full_messages
      redirect_to new_wine_path
    end

  end

  def edit
    #only admins can edit
    @wine = Wine.find(params[:id])
    @recipes = Recipe.all
    @user = User.find(session[:user_id])
    @wine.user_wines.find_or_create_by(user: @user)
  end

  def update
    @recipes = Recipe.all
    @user = User.find(session[:user_id])
    @wine = Wine.find(params[:id])
    if @wine.update(wine_params)
      redirect_to wine_path(@wine)
    else
      flash[:error] = @wine.errors.full_messages
      redirect_to edit_wine_path(@wine)
    end
  end

  def delete
    #only admins can delete
    @wine = Wine.find(params[:id])
    @wine.destroy
    redirect_to wines_path
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :year, :country, :price, user_wines_attributes: [:user_id, :rating], recipe_ids: [], recipes_attributes: [:name, :difficult_level, :cost])
  end
end

app/views/wines/_form.html.erb
<% if flash[:error] %>
  <ul><% flash[:error].each do |error| %>
    <li><%= error %></li>
  <% end %></ul>
<% end %>

<%= form_for @wine do |f| %>
  <p><%= f.label :name %>: <%= f.text_field :name %><br></p>
  <p><%= f.label :year %>: <%= f.number_field :year %><br></p>
  <p><%= f.label :country%>: <%= f.text_field :country %><br></p>
  <p><%= f.label :price %>: <%= f.number_field :price %><br></p>


<p><%= f.label :"Your Rating" %>:
    <%= f.fields_for :user_wines, @wine.user_wines.build do |wines_field| %>
    <%= wines_field.number_field :rating %>
    <%= wines_field.hidden_field :user_id, value: @user.id %>
    <% end %><br></p>

  <p><strong><%= f.label :"Select recipes to pair with wine:" %></strong></p>
  <%= f.collection_check_boxes :recipe_ids, @recipes, :id, :name do |b|%>
    <span>
      <%= b.check_box %>
      <%= b.label %><br>
    </span>
    <% end %>

  <p><strong><%= f.label :"Add a new recipe:" %></strong></p>
  <%= f.fields_for :recipes, @wine.recipes.build do |recipes_fields| %>
    <%= recipes_fields.text_field :name, placeholder: "Name" %>
    <%= recipes_fields.text_field :difficult_level, placeholder: "Diffulty Level"%>
    <%= recipes_fields.number_field :cost, placeholder: "Total Cost" %>
  <% end %><br>

  <p><%= f.submit %></p>
<% end %>

app/views/wines/edit.html.erb
<h1>Edit This Vino</h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1> All Vinos </h1>

<ul><% @wines.each do |wine| %>
  <li><%= link_to wine.name, wine %> </li>
  <% end %> </ul>

<p>Top Saved Wine: <%=link_to @top_saved.name, wine_path(@top_saved) %> </p>

<%= link_to "New Vino", new_wine_path %> | <%= link_to "All Recipes", recipes_path %>

app/views/wines/new.html.erb
<h1>New Vino</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<%if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1><%= @wine.name %></h1>

<p><strong>Country: </strong><%=@wine.country%></p>
<p><strong>Year: </strong><%=@wine.year%></p>
<p><strong>Price per Bottle: </strong>$<%=@wine.price%></p>
<p><strong>Average Rating: </strong><%=@rating%></p>
<p><strong>Your Rating: </strong><%=@user_rating%></p>


<p><strong> Recipes to go with this vino: </strong></p>

<ul> <% @wine.recipes.each do |recipe| %>
  <li><%= link_to recipe.name, recipe%> </li>
<% end %> </ul>
<% if !@user.user_wines.find_by(wine: @wine) %>
  <p>Do you want to save this wine?</p>
  <%= form_for @userwine do |f| %>
    <%= f.hidden_field :wine_id, value: @wine.id %>
     <%= f.number_field :rating, placeholder: "Your Rating (1-5)" %>
     <%= f.submit :"Yes, I want to save this wine" %>
    <% end %>
  <!-- <p><%=link_to "Yes!", user_wines_path(wine_id: @wine.id), method: :post%></p> -->
<% else %>
  <p> Do you want to delete this wine from your list? <%=link_to "Yes!", delete_user_wine_path(wine_id: @wine.id), method: :delete%></p>
  <%= link_to "Edit This Vino", edit_wine_path(@wine) %>
<%end %>