config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#index'
  get '/sessions', to: 'sessions#index'
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new",  as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: 'delete_session'
  delete "/recipes", to: "recipes#destroy", as: 'delete_recipe'
  delete "/userwines", to: "user_wines#destroy", as: 'delete_user_wine'
    delete "/friendships", to: "friendships#destroy", as: 'delete_friendship'

  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :wines
  resources :recipes
  resources :user_wines, only: [:index, :new, :create]
  resources :friendships, only: [:index, :new, :create]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Best Vino App Ever</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if current_user %>
          <a class="navbar-brand" href="<%= user_path(current_user) %>"/>Hello, <%=current_user.name%>!</a>
        <a class="navbar-brand" href="<%= wines_path %>"/>All Wines</a>
        <a class="navbar-brand" href="<%= users_path %>"/>Find Friends</a>
        <%= link_to("Logout", delete_session_path, {method: :delete, class: "navbar-brand"}) %>
        <% else %>
        <a class="navbar-brand" href="<%= signup_path %>"/>Sign Up</a>
        <a class="navbar-brand" href="<%= signin_path %>"/>Sign In</a>
        <% end %>


        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>